# -*- coding: utf-8 -*-
"""model_testing.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fr4GijNvTQcjZiWIrN90JimFkPArn79_
"""

import pandas as pd

df=pd.read_csv("test_preprocessing.csv")

X=df.drop("precipitation", axis=1)
y=df.precipitation

import pickle

filename = 'finalized_model.sav'

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X, y)
print(result)